export { default as imdbLogo} from './imdbLogo.png'
export { default as metacriticLogo } from './metacriticLogo.png'
export { default as rottenTomatoesLogo } from './rottenTomatoesLogo.png'
export { default as bBad } from './b-bad.jpeg'
export { default as bExcited} from './b-excited.jpeg'
export { default as bNeutral } from './b-neutral.jpeg'
export { default as bAwful } from './b-awful.jpeg'
export { default as dBad } from './d-bad.png'
export { default as dNeutral } from './d-neutral-0.jpeg'
export { default as dExcited } from './d-excited-0.jpeg'
